# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/infinix/Infinix_X6812/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Infinix_X6812)

endif
